// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: postrequest.proto

package protobufs;

public final class PostRequestProto {
  private PostRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufs_PostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobufs_PostRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021postrequest.proto\022\tprotobufs\"=\n\013PostRe" +
      "quest\022\016\n\006author\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\017\n\007" +
      "content\030\003 \001(\tB\024B\020PostRequestProtoP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobufs_PostRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobufs_PostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobufs_PostRequest_descriptor,
        new java.lang.String[] { "Author", "Title", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
