// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: postrequest.proto

package protobufs;

public interface PostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobufs.PostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string author = 1;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>optional string author = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>optional string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional string content = 3;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
